export interface Visa {
  c: string;
  f: string;
  r: string;
  d: string;
  dur: string;
  doc: string;
  p: string;
  fast: boolean;
}

export const VISA_DATA: Visa[] = [
  {c:"أوغندا / Uganda",f:"🇺🇬",r:"africa",d:"10 أيام",dur:"3 أشهر",doc:"جواز + صورة",p:"5,500",fast:false},
  {c:"تنزانيا / Tanzania",f:"🇹🇿",r:"africa",d:"15 يوم",dur:"3 أشهر",doc:"جواز + صورة",p:"5,500",fast:false},
  {c:"مدغشقر / Madagascar",f:"🇲🇬",r:"africa",d:"5 أيام",dur:"شهر",doc:"جواز + صورة",p:"4,500",fast:true},
  {c:"جيبوتي 15 يوم",f:"🇩🇯",r:"africa",d:"5 أيام",dur:"15 يوم",doc:"جواز + صورة",p:"2,500",fast:true},
  {c:"جيبوتي 3 أشهر",f:"🇩🇯",r:"africa",d:"5 أيام",dur:"3 أشهر",doc:"جواز + صورة",p:"4,500",fast:true},
  {c:"مالاوي شهر",f:"🇲🇼",r:"africa",d:"10 أيام",dur:"شهر",doc:"جواز + صورة",p:"5,500",fast:false},
  {c:"مالاوي 3 أشهر",f:"🇲🇼",r:"africa",d:"10 أيام",dur:"3 أشهر",doc:"جواز + صورة",p:"10,500",fast:false},
  {c:"توغو شهر",f:"🇹🇬",r:"africa",d:"10 أيام",dur:"شهر",doc:"جواز + صورة",p:"6,500",fast:false},
  {c:"توغو 3 أشهر",f:"🇹🇬",r:"africa",d:"10 أيام",dur:"3 أشهر",doc:"جواز + صورة",p:"8,500",fast:false},
  {c:"زامبيا / Zambia",f:"🇿🇲",r:"africa",d:"7 أيام",dur:"3 أشهر",doc:"جواز + صورة",p:"3,700",fast:false},
  {c:"بتسوانا شهر",f:"🇧🇼",r:"africa",d:"5 أيام",dur:"شهر",doc:"جواز + صورة",p:"5,000",fast:true},
  {c:"بتسوانا 3 أشهر",f:"🇧🇼",r:"africa",d:"5 أيام",dur:"3 أشهر",doc:"جواز + صورة",p:"6,500",fast:true},
  {c:"سيراليون / Sierra Leone",f:"🇸🇱",r:"africa",d:"10 أيام",dur:"شهر",doc:"جواز + صورة",p:"5,500",fast:false},
  {c:"غينيا الاستوائية",f:"🇬🇶",r:"africa",d:"5 أيام",dur:"3 أشهر",doc:"جواز + صورة",p:"7,500",fast:true},
  {c:"موزمبيق / Mozambique",f:"🇲🇿",r:"africa",d:"10 أيام",dur:"شهر",doc:"جواز + صورة",p:"6,500",fast:false},
  {c:"موريتانيا / Mauritania",f:"🇲🇷",r:"africa",d:"10 أيام",dur:"3 أشهر",doc:"جواز + صورة",p:"6,000",fast:false},
  {c:"سيشل / Seychelles",f:"🇸🇨",r:"africa",d:"5 أيام",dur:"3 أشهر",doc:"جواز + صورة",p:"5,000",fast:true},
  {c:"موريشيوس / Mauritius",f:"🇲🇺",r:"africa",d:"5 أيام",dur:"3 أشهر",doc:"جواز + صورة",p:"4,500",fast:true},
  {c:"كينيا / Kenya",f:"🇰🇪",r:"africa",d:"7 أيام",dur:"3 أشهر",doc:"جواز + صورة",p:"5,000",fast:false},
  {c:"تركيا / Turkey",f:"🇹🇷",r:"asia",d:"ساعة ⚡",dur:"شهر",doc:"جواز + صورة",p:"2,950",fast:true},
  {c:"البحرين أسبوعين",f:"🇧🇭",r:"asia",d:"7 أيام",dur:"أسبوعين",doc:"جواز + كشف حساب",p:"3,700",fast:false},
  {c:"البحرين 3 أشهر",f:"🇧🇭",r:"asia",d:"7 أيام",dur:"3 أشهر",doc:"جواز + كشف حساب",p:"4,700",fast:false},
  {c:"البحرين سنة",f:"🇧🇭",r:"asia",d:"7 أيام",dur:"سنة",doc:"جواز + كشف حساب",p:"9,000",fast:false},
  {c:"جورجيا / Georgia",f:"🇬🇪",r:"asia",d:"7 أيام",dur:"شهر",doc:"جواز + صورة",p:"2,800",fast:false},
  {c:"أوزبكستان / Uzbekistan",f:"🇺🇿",r:"asia",d:"5 أيام",dur:"شهر",doc:"جواز + صورة",p:"3,500",fast:true},
  {c:"تايلاند / Thailand",f:"🇹🇭",r:"asia",d:"15 يوم",dur:"شهرين",doc:"جواز + صورة + خطاب عمل + تأمين + كشف حساب",p:"3,500",fast:false},
  {c:"إندونيسيا / Indonesia",f:"🇮🇩",r:"asia",d:"5 أيام",dur:"شهر",doc:"جواز + صورة",p:"4,000",fast:true},
  {c:"سنغافورة / Singapore",f:"🇸🇬",r:"asia",d:"7 أيام",dur:"شهر",doc:"جواز + صورة + كشف حساب",p:"5,500",fast:false},
  {c:"الفلبين / Philippines",f:"🇵🇭",r:"asia",d:"7 أيام",dur:"30 يوم",doc:"جواز + صورة",p:"5,500",fast:false},
  {c:"الصين / China",f:"🇨🇳",r:"asia",d:"10 أيام",dur:"حسب السفارة",doc:"جواز + صورة + كشف حساب + خطاب وظيفي",p:"2,500 تجهيز",fast:false},
  {c:"اليابان / Japan",f:"🇯🇵",r:"asia",d:"10 أيام",dur:"حسب السفارة",doc:"جواز + كشف 6 أشهر + صورة + خطاب عمل + تأمين",p:"2,500 + 26$",fast:false},
  {c:"كمبوديا / Cambodia",f:"🇰🇭",r:"asia",d:"7 أيام",dur:"شهر",doc:"جواز + صورة",p:"3,700",fast:false},
  {c:"نيبال / Nepal",f:"🇳🇵",r:"asia",d:"5 أيام",dur:"شهر",doc:"جواز + صورة",p:"5,000",fast:true},
  {c:"لاوس / Laos",f:"🇱🇦",r:"asia",d:"10 أيام",dur:"شهر",doc:"جواز + صورة",p:"5,000",fast:false},
  {c:"ميانمار / Myanmar",f:"🇲🇲",r:"asia",d:"5 أيام",dur:"شهر",doc:"جواز + صورة",p:"5,000",fast:true},
  {c:"فيتنام مرة",f:"🇻🇳",r:"asia",d:"10 أيام",dur:"شهر",doc:"جواز + صورة",p:"4,500",fast:false},
  {c:"فيتنام متعددة",f:"🇻🇳",r:"asia",d:"10 أيام",dur:"شهر",doc:"جواز + صورة",p:"6,500",fast:false},
  {c:"طاجيكستان / Tajikistan",f:"🇹🇯",r:"asia",d:"14 يوم",dur:"شهرين",doc:"جواز + صورة",p:"3,700",fast:false},
  {c:"قيرغيزستان / Kyrgyzstan",f:"🇰🇬",r:"asia",d:"15 يوم",dur:"شهر",doc:"جواز + صورة",p:"5,500",fast:false},
  {c:"ألبانيا / Albania",f:"🇦🇱",r:"europe",d:"25 يوم",dur:"شهر",doc:"جواز + صورة + خطاب وظيفي + كشف بنكي 12 شهر",p:"5,500 + 7,000",fast:false},
  {c:"كوبا مصريين / Cuba EG",f:"🇨🇺",r:"americas",d:"48 ساعة",dur:"3 أشهر",doc:"صورة جواز",p:"7,000",fast:true},
  {c:"كوبا غير مصريين",f:"🇨🇺",r:"americas",d:"48 ساعة",dur:"3 أشهر",doc:"صورة جواز",p:"10,000",fast:true},
  {c:"سورينام مصريين",f:"🇸🇷",r:"americas",d:"15 يوم",dur:"3 أشهر",doc:"جواز + صورة + خطاب وظيفي + كشف حساب",p:"9,000",fast:false},
  {c:"سورينام غير مصريين",f:"🇸🇷",r:"americas",d:"48 ساعة",dur:"3 أشهر",doc:"جواز + صورة",p:"9,000",fast:true},
  {c:"جزر البهاما / Bahamas",f:"🇧🇸",r:"americas",d:"20 يوم",dur:"3 أشهر",doc:"جواز + صورة + خطاب وظيفي + كشف حساب + فيش جنائي + كشف طبي",p:"10,500 + 4,000",fast:false},
  {c:"كولومبيا / Colombia",f:"🇨🇴",r:"americas",d:"20 يوم",dur:"3 أشهر",doc:"جواز + صورة + كشف حساب + خطاب عمل",p:"6,500 + 8,500",fast:false},
  {c:"البرازيل / Brazil",f:"🇧🇷",r:"americas",d:"حسب الموعد",dur:"حسب السفارة",doc:"جواز + صورة + كشف حساب + خطاب عمل + تأمين + فيش جنائي",p:"4,000 + 80$",fast:false},
  {c:"بوليفيا / Bolivia",f:"🇧🇴",r:"americas",d:"7-10 أيام",dur:"حسب السفارة",doc:"جواز + صورة + كشف حساب + خطاب عمل + تأمين",p:"2,500",fast:false},
  {c:"سانت كيتس / St. Kitts",f:"🇰🇳",r:"americas",d:"15 يوم",dur:"3 أشهر",doc:"جواز + صورة + كشف حساب + خطاب وظيفي",p:"8,000 + 5,000",fast:false},
  {c:"ترينيداد وتوباغو",f:"🇹🇹",r:"americas",d:"15 يوم",dur:"3 أشهر",doc:"جواز + صورة + كشف 6 أشهر + خطاب عمل + تأمين",p:"6,000 + 5,000",fast:false},
  {c:"أنتيغوا / Antigua",f:"🇦🇬",r:"americas",d:"15 يوم",dur:"شهر",doc:"جواز + صورة + كشف 6 أشهر + خطاب عمل + فيش جنائي",p:"6,000 + 5,000",fast:false},
  {c:"غويانا / Guyana",f:"🇬🇾",r:"americas",d:"15 يوم",dur:"3 أشهر",doc:"جواز + صورة + كشف 6 أشهر + خطاب عمل + فيش جنائي",p:"6,500 + 25$",fast:false},
  {c:"أستراليا / Australia",f:"🇦🇺",r:"oceania",d:"من 30 يوم",dur:"سنة متعددة",doc:"جواز + صورة + إثبات مالي + تأمين طبي + أملاك في مصر",p:"13,000 + 4,000",fast:false},
  {c:"نيوزيلندا / New Zealand",f:"🇳🇿",r:"oceania",d:"30 يوم عمل",dur:"حسب السفارة",doc:"جواز + صورة + إثبات مالي + تأمين طبي + أملاك + تأشيرات سابقة",p:"20,000 + 4,000",fast:false},
];

export const IMGS_URL: Record<string, string> = {
  '🇺🇬':'https://loremflickr.com/600/400/Uganda,landmark/all',
  '🇹🇿':'https://loremflickr.com/600/400/Tanzania,landmark/all',
  '🇲🇬':'https://loremflickr.com/600/400/Madagascar,landmark/all',
  '🇩🇯':'https://loremflickr.com/600/400/Djibouti,landmark/all',
  '🇲🇼':'https://loremflickr.com/600/400/Malawi,landmark/all',
  '🇹🇬':'https://loremflickr.com/600/400/Togo,landmark/all',
  '🇿🇲':'https://loremflickr.com/600/400/Zambia,landmark/all',
  '🇧🇼':'https://loremflickr.com/600/400/Botswana,landmark/all',
  '🇸🇱':'https://loremflickr.com/600/400/SierraLeone,landmark/all',
  '🇬🇶':'https://loremflickr.com/600/400/EquatorialGuinea,landmark/all',
  '🇲🇿':'https://loremflickr.com/600/400/Mozambique,landmark/all',
  '🇲🇷':'https://loremflickr.com/600/400/Mauritania,landmark/all',
  '🇸🇨':'https://loremflickr.com/600/400/Seychelles,landmark/all',
  '🇲🇺':'https://loremflickr.com/600/400/Mauritius,landmark/all',
  '🇰🇪':'https://loremflickr.com/600/400/Kenya,landmark/all',
  '🇹🇷':'https://loremflickr.com/600/400/Turkey,landmark/all',
  '🇧🇭':'https://loremflickr.com/600/400/Bahrain,landmark/all',
  '🇬🇪':'https://loremflickr.com/600/400/Georgia,landmark/all',
  '🇺🇿':'https://loremflickr.com/600/400/Uzbekistan,landmark/all',
  '🇹🇭':'https://loremflickr.com/600/400/Thailand,landmark/all',
  '🇮🇩':'https://loremflickr.com/600/400/Indonesia,landmark/all',
  '🇸🇬':'https://loremflickr.com/600/400/Singapore,landmark/all',
  '🇵🇭':'https://loremflickr.com/600/400/Philippines,landmark/all',
  '🇨🇳':'https://loremflickr.com/600/400/China,landmark/all',
  '🇯🇵':'https://loremflickr.com/600/400/Japan,landmark/all',
  '🇰🇭':'https://loremflickr.com/600/400/Cambodia,landmark/all',
  '🇳🇵':'https://loremflickr.com/600/400/Nepal,landmark/all',
  '🇱🇦':'https://loremflickr.com/600/400/Laos,landmark/all',
  '🇲🇲':'https://loremflickr.com/600/400/Myanmar,landmark/all',
  '🇻🇳':'https://loremflickr.com/600/400/Vietnam,landmark/all',
  '🇹🇯':'https://loremflickr.com/600/400/Tajikistan,landmark/all',
  '🇰🇬':'https://loremflickr.com/600/400/Kyrgyzstan,landmark/all',
  '🇦🇱':'https://loremflickr.com/600/400/Albania,landmark/all',
  '🇨🇺':'https://loremflickr.com/600/400/Cuba,landmark/all',
  '🇸🇷':'https://loremflickr.com/600/400/Suriname,landmark/all',
  '🇧🇸':'https://loremflickr.com/600/400/Bahamas,landmark/all',
  '🇨🇴':'https://loremflickr.com/600/400/Colombia,landmark/all',
  '🇧🇷':'https://loremflickr.com/600/400/Brazil,landmark/all',
  '🇧🇴':'https://loremflickr.com/600/400/Bolivia,landmark/all',
  '🇰🇳':'https://loremflickr.com/600/400/StKitts,landmark/all',
  '🇹🇹':'https://loremflickr.com/600/400/Trinidad,landmark/all',
  '🇦🇬':'https://loremflickr.com/600/400/Antigua,landmark/all',
  '🇬🇾':'https://loremflickr.com/600/400/Guyana,landmark/all',
  '🇦🇺':'https://loremflickr.com/600/400/Australia,landmark/all',
  '🇳🇿':'https://loremflickr.com/600/400/NewZealand,landmark/all',
};
